### ISSUE TITLE
Implement delete operation in Epics page

### ISSUE THREAD

**Issue by buremba** [umitkucuk/vue-playground#4]
The Epics table should have an additional column with the link `Delete row`. When the user clicks the link you need to prompt an alertbox to the user (http://element.eleme.io/#/en-US/component/message-box#confirm) for confirmation and if the user wants to delete the row you need to perform an API call to the server and remove that row using its id.
You should show a loading icon (http://element.eleme.io/#/en-US/component/button#loading-button) during the API call.

**Comment by umitkucuk** [comment]
Task has been completed by fc6bb348e65bb3f1187c962365a50c75bfd48cdf.

**Comment by buremba** [comment]
👌🏽
